site_name: Min side utvikler-docs
site_url: https://tms-dokumentasjon.intern.nav.no #TODO fikse forskjellige url-er
nav:
  - Forside: index.md
  - Utkast: utkast.md
  - Microforntend: microfrontend.md
  - Varsler:
      - Varsler: varsler/index.md
      - Produsere varsler: varsler/produsere.md
      - Konsumere varsler: varsler/konsumere.md
      - Migrere fra AVRO: varsler/migrere.md


plugins:
  - search
  - external-markdown