site_name: Min side utvikler-docs
nav:
  - Innholdsguide: guide.md
  - Utkast: utkast.md
  - Microfrontend: microfrontend.md
  - Varsler:
      - Oversikt: varsler/index.md
      - Produsere varsler: varsler/produsere.md
      - Konsumere varsler: varsler/konsumere.md
      - Migrere fra AVRO: varsler/migrere.md
  - Søknadskvittering (WIP): soknadskvittering.md
not_in_nav: index.md

extra_css:
  - styles/styles.css
  - styles/navbar.css
  - styles/page-content.css
  - styles/toc.css
  - styles/search-modal.css
  - styles/footer.css
extra_javascript:
  - scripts/override_navbar-background.js

plugins:
  - search
  - external-markdown
theme:
  name: mkdocs
  navigation_depth: 3
  locale: nb
  custom_dir: docs/custom_theme
markdown_extensions:
  nl2br: { }
