name: "Build and deploy"
on:
  push:
    branches:
      - "main"
env:
  "IMAGE": "ghcr.io/${{ github.repository }}/tms-dokumentasjon:${{ github.sha }}"
  "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
  VERSION_NAME= $(date +'%Y%m%d%H%M%S')

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3"
      - name: "Build and publish Docker image"
        run:
          "docker build --build-arg READ_TOKEN=${{ secrets.READER_TOKEN }} --tag ${IMAGE}$VERSION_NAME  .
          \ && echo $GITHUB_TOKEN | docker login  --username $GITHUB_REPOSITORY --password-stdin https://ghcr.io\
          \ && docker push ${IMAGE}$VERSION_NAME"

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-latest"
    needs: "build"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Deploy to prod"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/prod-gcp/nais.yaml