name: "Build and deploy"
on:
  push:
    branches:
      - "main"
env:
  "IMAGE": "ghcr.io/${{ github.repository }}/tms-dokumentasjon:${{ github.sha }}"
  "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    outputs:
      image_tag: ${{ env.IMAGE_TAG }}
    steps:
      - uses: "actions/checkout@v3"
      - name: "Build and publish Docker image"
        run: |
          VERSION_NAME=$(date +'%Y%m%d%H%M%S')
          IMAGE_TAG=$IMAGE$VERSION_NAME
          docker build --build-arg READ_TOKEN=${{ secrets.READER_TOKEN }} --tag ${IMAGE_TAG}  .
          echo $GITHUB_TOKEN | docker login  --username $GITHUB_REPOSITORY --password-stdin https://ghcr.io
          docker push ${IMAGE_TAG}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-latest"
    needs: "build"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Deploy to prod"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/prod-gcp/nais.yaml
          VAR: version=${{ needs.build.outputs.image_tag }}